#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : hunspell
Version  : 1.6.1
Release  : 1
URL      : https://github.com/hunspell/hunspell/archive/v1.6.1.tar.gz
Source0  : https://github.com/hunspell/hunspell/archive/v1.6.1.tar.gz
Summary  : Hunspell spellchecking library
Group    : Development/Tools
License  : BSD-2-Clause GPL-3.0 LGPL-2.1 LGPL-3.0 MPL-1.1
Requires: hunspell-bin
Requires: hunspell-lib
Requires: hunspell-data
Requires: hunspell-doc
BuildRequires : bison

%description
About Hunspell
==============
NOTICE: Verison 2 is in the works. For contributing see
[version 2 specification][v2spec] and the folder `src/hunspell2`.

%package bin
Summary: bin components for the hunspell package.
Group: Binaries
Requires: hunspell-data

%description bin
bin components for the hunspell package.


%package data
Summary: data components for the hunspell package.
Group: Data

%description data
data components for the hunspell package.


%package dev
Summary: dev components for the hunspell package.
Group: Development
Requires: hunspell-lib
Requires: hunspell-bin
Requires: hunspell-data
Provides: hunspell-devel

%description dev
dev components for the hunspell package.


%package doc
Summary: doc components for the hunspell package.
Group: Documentation

%description doc
doc components for the hunspell package.


%package lib
Summary: lib components for the hunspell package.
Group: Libraries
Requires: hunspell-data

%description lib
lib components for the hunspell package.


%prep
%setup -q -n hunspell-1.6.1

%build
export LANG=C
export SOURCE_DATE_EPOCH=1491846551
%reconfigure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1491846551
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/affixcompress
/usr/bin/analyze
/usr/bin/chmorph
/usr/bin/hunspell
/usr/bin/hunzip
/usr/bin/hzip
/usr/bin/ispellaff2myspell
/usr/bin/makealias
/usr/bin/munch
/usr/bin/unmunch
/usr/bin/wordforms
/usr/bin/wordlist2hunspell

%files data
%defattr(-,root,root,-)
/usr/share/man/hu/man1/hunspell.1

%files dev
%defattr(-,root,root,-)
/usr/include/hunspell/atypes.hxx
/usr/include/hunspell/csutil.hxx
/usr/include/hunspell/htypes.hxx
/usr/include/hunspell/hunspell.h
/usr/include/hunspell/hunspell.hxx
/usr/include/hunspell/hunvisapi.h
/usr/include/hunspell/w_char.hxx
/usr/lib64/libhunspell-1.6.so
/usr/lib64/pkgconfig/hunspell.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
%doc /usr/share/man/man3/*
%doc /usr/share/man/man5/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libhunspell-1.6.so.0
/usr/lib64/libhunspell-1.6.so.0.0.1
