#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : hunspell
Version  : 1.7.1
Release  : 9
URL      : https://github.com/hunspell/hunspell/archive/v1.7.1/hunspell-1.7.1.tar.gz
Source0  : https://github.com/hunspell/hunspell/archive/v1.7.1/hunspell-1.7.1.tar.gz
Summary  : Hunspell spellchecking library
Group    : Development/Tools
License  : BSD-2-Clause GPL-2.0 LGPL-2.1 MPL-1.1
Requires: hunspell-bin = %{version}-%{release}
Requires: hunspell-lib = %{version}-%{release}
Requires: hunspell-license = %{version}-%{release}
Requires: hunspell-man = %{version}-%{release}

%description
# About Hunspell
Hunspell is a free spell checker and morphological analyzer library
and command-line tool, licensed under LGPL/GPL/MPL tri-license.

%package bin
Summary: bin components for the hunspell package.
Group: Binaries
Requires: hunspell-license = %{version}-%{release}

%description bin
bin components for the hunspell package.


%package dev
Summary: dev components for the hunspell package.
Group: Development
Requires: hunspell-lib = %{version}-%{release}
Requires: hunspell-bin = %{version}-%{release}
Provides: hunspell-devel = %{version}-%{release}
Requires: hunspell = %{version}-%{release}

%description dev
dev components for the hunspell package.


%package lib
Summary: lib components for the hunspell package.
Group: Libraries
Requires: hunspell-license = %{version}-%{release}

%description lib
lib components for the hunspell package.


%package license
Summary: license components for the hunspell package.
Group: Default

%description license
license components for the hunspell package.


%package man
Summary: man components for the hunspell package.
Group: Default

%description man
man components for the hunspell package.


%prep
%setup -q -n hunspell-1.7.1
cd %{_builddir}/hunspell-1.7.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1661355691
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1661355691
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/hunspell
cp %{_builddir}/hunspell-%{version}/COPYING %{buildroot}/usr/share/package-licenses/hunspell/13d2034b5ee3cb8d1a076370cf8f0e344a5d0855
cp %{_builddir}/hunspell-%{version}/COPYING.LESSER %{buildroot}/usr/share/package-licenses/hunspell/5dea8b07199dbcc7be918770ca7cef346f523214
cp %{_builddir}/hunspell-%{version}/COPYING.MPL %{buildroot}/usr/share/package-licenses/hunspell/aba8d76d0af67d57da3c3c321caa59f3d242386b
cp %{_builddir}/hunspell-%{version}/license.myspell %{buildroot}/usr/share/package-licenses/hunspell/a897c88546c86e1f1eaebd89bc101404d51e81cc
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/affixcompress
/usr/bin/analyze
/usr/bin/chmorph
/usr/bin/hunspell
/usr/bin/hunzip
/usr/bin/hzip
/usr/bin/ispellaff2myspell
/usr/bin/makealias
/usr/bin/munch
/usr/bin/unmunch
/usr/bin/wordforms
/usr/bin/wordlist2hunspell

%files dev
%defattr(-,root,root,-)
/usr/include/hunspell/atypes.hxx
/usr/include/hunspell/hunspell.h
/usr/include/hunspell/hunspell.hxx
/usr/include/hunspell/hunvisapi.h
/usr/include/hunspell/w_char.hxx
/usr/lib64/libhunspell-1.7.so
/usr/lib64/pkgconfig/hunspell.pc
/usr/share/man/man3/hunspell.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libhunspell-1.7.so.0
/usr/lib64/libhunspell-1.7.so.0.0.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/hunspell/13d2034b5ee3cb8d1a076370cf8f0e344a5d0855
/usr/share/package-licenses/hunspell/5dea8b07199dbcc7be918770ca7cef346f523214
/usr/share/package-licenses/hunspell/a897c88546c86e1f1eaebd89bc101404d51e81cc
/usr/share/package-licenses/hunspell/aba8d76d0af67d57da3c3c321caa59f3d242386b

%files man
%defattr(0644,root,root,0755)
/usr/share/man/hu/man1/hunspell.1
/usr/share/man/man1/hunspell.1
/usr/share/man/man1/hunzip.1
/usr/share/man/man1/hzip.1
/usr/share/man/man5/hunspell.5
